-- SQL*Plus environment settings for better logging output
SET DEFINE OFF;
SET FEEDBACK ON;
SET ECHO ON;
SET VERIFY ON;
SET SERVEROUTPUT ON;


-- Cleanup: Drop existing tables to ensure a clean state
BEGIN
    -- Disable constraints to avoid dependency errors during drop
    FOR i IN (SELECT constraint_name, table_name FROM user_constraints WHERE constraint_type = 'R') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE ' || i.table_name || ' DROP CONSTRAINT ' || i.constraint_name;
    END LOOP;

    -- Drop all tables
    FOR i IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || i.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- ------------------------------------------------------------------
-- Table: aviacompany
-- Purpose: Stores airline details including headquarters and fleet metrics.
-- ------------------------------------------------------------------


CREATE TABLE aviacompany (
    id_company NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 200) PRIMARY KEY,
    company_name VARCHAR2(256) NOT NULL ,
    headquarters VARCHAR2(256) NOT NULL ,
    founding_date DATE NOT NULL ,
    fleet_size NUMBER NOT NULL
);


-- ------------------------------------------------------------------
-- Table: employee
-- Purpose: Base table for all airport and airline personnel.
-- ------------------------------------------------------------------

CREATE TABLE employee(
    id_employee NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 200) PRIMARY KEY,
    id_company NUMBER,
    full_name VARCHAR2(256) NOT NULL,
    position VARCHAR2(256) NOT NULL,
    hire_date DATE NOT NULL,
    salary NUMBER NOT NULL,
    CONSTRAINT fk_employee_aviacompany FOREIGN KEY (id_company)
        REFERENCES aviacompany (id_company) ON DELETE CASCADE
);


-- ------------------------------------------------------------------
-- Table: stewardess
-- Subtype of employee
-- ------------------------------------------------------------------
CREATE TABLE stewardess (
    id_employee     NUMBER PRIMARY KEY,
    qualification   VARCHAR2(256) NOT NULL,
    CONSTRAINT fk_stewardess_employee FOREIGN KEY (id_employee)
        REFERENCES employee (id_employee) ON DELETE CASCADE
);

-- ------------------------------------------------------------------
-- Table: pilot
-- Purpose: Specialized employee data for flight crew.
-- ------------------------------------------------------------------

CREATE TABLE pilot (
    id_employee NUMBER PRIMARY KEY,
    license_number VARCHAR2(50) NOT NULL,
    qualification VARCHAR2(256) NOT NULL,
    flight_hours NUMBER NOT NULL,
    CONSTRAINT fk_pilot_employee FOREIGN KEY (id_employee)
        REFERENCES employee (id_employee) ON DELETE CASCADE
);

-- ------------------------------------------------------------------
-- Table: passenger
-- Purpose: Client personal information for ticket booking.
-- ------------------------------------------------------------------

CREATE TABLE passenger (
    id_passenger NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 200) PRIMARY KEY,
    city VARCHAR2(256) NOT NULL,
    full_name VARCHAR2(256) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR2(10) NOT NULL
);

-- ------------------------------------------------------------------
-- Table: plane
-- Purpose: Technical specifications of aircraft fleet.
-- ------------------------------------------------------------------
CREATE TABLE plane(
    id_plane NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 200) PRIMARY KEY,
    id_company NUMBER NOT NULL,
    model VARCHAR2(256) NOT NULL,
    capacity NUMBER NOT NULL,
    year_of_manufacture NUMBER NOT NULL,
    CONSTRAINT fk_plane_aviacompany FOREIGN KEY (id_company)
        REFERENCES aviacompany (id_company) ON DELETE CASCADE
);

-- ------------------------------------------------------------------
-- Table: flight
-- Purpose: Flight schedule tracking departure and arrival times.
-- ------------------------------------------------------------------
CREATE TABLE flight(
    id_flight NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 200) PRIMARY KEY,
    id_plane NUMBER NOT NULL,
    departure_time TIMESTAMP NOT NULL,
    arrival_time TIMESTAMP NOT NULL,
    duration NUMBER NOT NULL,
    status VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_flight_plane FOREIGN KEY (id_plane)
        REFERENCES plane (id_plane) ON DELETE CASCADE
);

-- ------------------------------------------------------------------
-- Table: ticket
-- Purpose: Links passengers to flights with seat and pricing data.
-- ------------------------------------------------------------------
CREATE TABLE ticket (
    id_ticket       NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 200) PRIMARY KEY,
    id_passenger    NUMBER NOT NULL,
    id_flight       NUMBER,
    seat_number     VARCHAR2(50) NOT NULL,
    class           VARCHAR2(50) NOT NULL,
    price           NUMBER NOT NULL,
    CONSTRAINT fk_ticket_passenger FOREIGN KEY (id_passenger)
        REFERENCES passenger (id_passenger) ON DELETE CASCADE,
    CONSTRAINT fk_ticket_flight FOREIGN KEY (id_flight)
        REFERENCES flight (id_flight) ON DELETE SET NULL
);


-- ------------------------------------------------------------------
-- Table: baggage
-- ------------------------------------------------------------------
CREATE TABLE baggage (
    id_baggage      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 200) PRIMARY KEY,
    id_ticket       NUMBER NOT NULL,
    weight          NUMBER NOT NULL,
    height          NUMBER NOT NULL,
    status          VARCHAR2(50) NOT NULL,
    luggage_type    VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_baggage_ticket FOREIGN KEY (id_ticket)
        REFERENCES ticket (id_ticket) ON DELETE CASCADE
);

-- ------------------------------------------------------------------
-- Table: pilot_flight (Junction Table)
-- ------------------------------------------------------------------

CREATE TABLE pilot_flight (
    id_employee     NUMBER NOT NULL,
    id_flight       NUMBER NOT NULL,
    position        VARCHAR2(256) NOT NULL,
    PRIMARY KEY (id_employee, id_flight),
    CONSTRAINT fk_pf_pilot FOREIGN KEY (id_employee) REFERENCES pilot (id_employee) ON DELETE CASCADE,
    CONSTRAINT fk_pf_flight FOREIGN KEY (id_flight) REFERENCES flight (id_flight) ON DELETE CASCADE
);


-- ------------------------------------------------------------------
-- Table: stewardess_flight (Junction Table)
-- ------------------------------------------------------------------
CREATE TABLE stewardess_flight (
    id_employee     NUMBER NOT NULL,
    id_flight       NUMBER NOT NULL,
    feedback        NUMBER NOT NULL,
    service_date    DATE NOT NULL,
    PRIMARY KEY (id_employee, id_flight),
    CONSTRAINT fk_sf_stewardess FOREIGN KEY (id_employee) REFERENCES stewardess (id_employee) ON DELETE CASCADE,
    CONSTRAINT fk_sf_flight FOREIGN KEY (id_flight) REFERENCES flight (id_flight) ON DELETE CASCADE
);


-- ------------------------------------------------------------------
-- IO 1: Trigger to prevent pilot flight time overlapping
-- ------------------------------------------------------------------


CREATE OR REPLACE TRIGGER trg_pilot_flight_overlap
FOR INSERT OR UPDATE ON pilot_flight
COMPOUND TRIGGER

    -- Collection to store existing flight schedules
    TYPE t_schedule_rec IS RECORD
                            (
                            id_employee NUMBER,
                            start_t TIMESTAMP,
                            end_t TIMESTAMP
                           );
    TYPE t_schedule_tab IS TABLE OF t_schedule_rec;
    v_schedules t_schedule_tab;

    BEFORE STATEMENT IS
    BEGIN
        SELECT pf.id_employee, f.departure_time, f.arrival_time
        BULK COLLECT INTO v_schedules
        FROM pilot_flight pf
        JOIN flight f ON pf.id_flight = f.id_flight;
    END BEFORE STATEMENT;

    -- Step 2: Check each new row against the loaded schedules
    AFTER EACH ROW IS
        v_new_start TIMESTAMP;
        v_new_end   TIMESTAMP;
    BEGIN
        -- Get times for the current inserting/updating flight
        SELECT departure_time, arrival_time INTO v_new_start, v_new_end
        FROM flight WHERE id_flight = :NEW.id_flight;

        FOR i IN 1 .. v_schedules.COUNT LOOP
            -- Check only for the same pilot, excluding the current record itself if updating
            IF v_schedules(i).id_employee = :NEW.id_employee THEN
                IF (v_new_start < v_schedules(i).end_t AND v_new_end > v_schedules(i).start_t) THEN
                    RAISE_APPLICATION_ERROR(-20001, 'IO Violation: Pilot ID ' || :NEW.id_employee || ' has an overlapping flight.');
                END IF;
            END IF;
        END LOOP;
    END AFTER EACH ROW;



END trg_pilot_flight_overlap;
/


-- ------------------------------------------------------------------
-- IO 2: Trigger to prevent overselling tickets (Aircraft Capacity)
-- Implementation based on Lecture Section 9.4
-- ------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_ticket_capacity
FOR INSERT ON ticket
COMPOUND TRIGGER

    TYPE t_count_tab IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    v_ticket_counts t_count_tab;

    -- Step 1: Count current tickets for all flights
    BEFORE STATEMENT IS
    BEGIN
        FOR r IN (SELECT id_flight, COUNT(*) as cnt FROM ticket GROUP BY id_flight) LOOP
            v_ticket_counts(r.id_flight) := r.cnt;
        END LOOP;
    END BEFORE STATEMENT;

    -- Step 2: Check capacity for each new ticket
    BEFORE EACH ROW IS
        v_capacity NUMBER;
        v_current  NUMBER := 0;
    BEGIN
        -- Get plane capacity for this flight
        SELECT p.capacity INTO v_capacity
        FROM flight f
        JOIN plane p ON f.id_plane = p.id_plane
        WHERE f.id_flight = :NEW.id_flight;

        IF v_ticket_counts.EXISTS(:NEW.id_flight) THEN
            v_current := v_ticket_counts(:NEW.id_flight);
        END IF;

        IF v_current >= v_capacity THEN
            RAISE_APPLICATION_ERROR(-20002, 'IO Violation: Flight ' || :NEW.id_flight || ' is full (Capacity: ' || v_capacity || ').');
        END IF;

        -- Update internal counter for the next row in same statement
        v_ticket_counts(:NEW.id_flight) := v_current + 1;
    END BEFORE EACH ROW;
END trg_ticket_capacity;
/